// ─── ПРОЕКТЫ (95 объектов из Excel) ──────────────────────────────────────────
export const projects = [
  {
    id: 1,
    title: "Дом из газобетона (Аннинское)",
    nameOrig: "Аннинское",
    material: "Газобетон",
    area: 486,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "10,9 млн ₽",
    image: "/images/projects/anninskoe/photo-1.jpg",
    images: ["/images/projects/anninskoe/photo-1.jpg", "/images/projects/anninskoe/photo-2.jpg", "/images/projects/anninskoe/photo-3.jpg", "/images/projects/anninskoe/photo-4.jpg", "/images/projects/anninskoe/photo-5.jpg", "/images/projects/anninskoe/photo-6.jpg"],
    plans: ["/images/projects/anninskoe/plan-1.jpg", "/images/projects/anninskoe/plan-2.jpg"],
    slug: "anninskoe",
    tags: ["gazobeton"],
    description: "3 ТЕРРАСЫ; 2 КРЫЛЬЦА; КАБИНЕТ; СКЛАД; ГАРАЖ; КОТЕЛЬНАЯ; ХОЗ.ПОМЕЩЕНИЕ; ЛАУНЖ ЗОНА; ПОСТИРОЧНАЯ",
  },
  {
    id: 2,
    title: "Дом из газобетона (Абрикосовая)",
    nameOrig: "Абрикосовая",
    material: "Газобетон",
    area: 186,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,4 млн ₽",
    image: "/images/projects/abrikosovaya/photo-1.jpg",
    images: ["/images/projects/abrikosovaya/photo-1.jpg", "/images/projects/abrikosovaya/photo-2.jpg", "/images/projects/abrikosovaya/photo-3.jpg", "/images/projects/abrikosovaya/photo-4.jpg"],
    plans: ["/images/projects/abrikosovaya/plan-1.jpg", "/images/projects/abrikosovaya/plan-2.jpg"],
    slug: "abrikosovaya",
    tags: ["gazobeton"],
    description: "Терраса; Котельная; Кладовая; Парная; Гардеробная; Балкон",
  },
  {
    id: 3,
    title: "Дом из газобетона (Агалатово)",
    nameOrig: "Агалатово",
    material: "Газобетон",
    area: 179,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6,3 млн ₽",
    image: "/images/projects/agalatovo/photo-1.jpeg",
    images: ["/images/projects/agalatovo/photo-1.jpeg", "/images/projects/agalatovo/photo-2.jpeg", "/images/projects/agalatovo/photo-3.jpeg", "/images/projects/agalatovo/photo-4.jpeg", "/images/projects/agalatovo/photo-5.jpeg", "/images/projects/agalatovo/photo-6.jpeg", "/images/projects/agalatovo/photo-7.jpg", "/images/projects/agalatovo/photo-8.jpg", "/images/projects/agalatovo/photo-9.jpg"],
    plans: ["/images/projects/agalatovo/plan-1.jpg"],
    slug: "agalatovo",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Терраса",
  },
  {
    id: 4,
    title: "Дом из клееного бруса (Агалатово 2)",
    nameOrig: "Агалатово 2",
    material: "Клееный брус",
    area: 318,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "13,4 млн ₽",
    image: "/images/projects/agalatovo-2/photo-1.jpg",
    images: ["/images/projects/agalatovo-2/photo-1.jpg", "/images/projects/agalatovo-2/photo-2.jpeg", "/images/projects/agalatovo-2/photo-3.jpeg", "/images/projects/agalatovo-2/photo-4.jpeg", "/images/projects/agalatovo-2/photo-5.jpeg", "/images/projects/agalatovo-2/photo-6.jpg", "/images/projects/agalatovo-2/photo-7.jpg", "/images/projects/agalatovo-2/photo-8.jpg", "/images/projects/agalatovo-2/photo-9.jpg"],
    plans: ["/images/projects/agalatovo-2/plan-1.jpg", "/images/projects/agalatovo-2/plan-2.jpg"],
    slug: "agalatovo-2",
    tags: ["brus"],
    description: "Терраса; Кладовая; Сауна; Постирочная; Кабинет; Балкон",
  },
  {
    id: 5,
    title: "Дом из газобетона (Акватория)",
    nameOrig: "Акватория",
    material: "Газобетон",
    area: 85,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "3,7 млн ₽",
    image: "/images/projects/akvatoriya/photo-1.jpg",
    images: ["/images/projects/akvatoriya/photo-1.jpg", "/images/projects/akvatoriya/photo-2.jpg", "/images/projects/akvatoriya/photo-3.jpg", "/images/projects/akvatoriya/photo-4.jpg", "/images/projects/akvatoriya/photo-5.jpg", "/images/projects/akvatoriya/photo-6.jpg", "/images/projects/akvatoriya/photo-7.jpg", "/images/projects/akvatoriya/photo-8.jpg", "/images/projects/akvatoriya/photo-9.jpg"],
    plans: ["/images/projects/akvatoriya/plan-1.jpg"],
    slug: "akvatoriya",
    tags: ["gazobeton"],
    description: "Котельная; Терраса",
  },
  {
    id: 6,
    title: "Дом из газобетона (Белоостров)",
    nameOrig: "Белоостров",
    material: "Газобетон",
    area: 180,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7,1 млн ₽",
    image: "/images/projects/beloostrov/photo-1.jpg",
    images: ["/images/projects/beloostrov/photo-1.jpg", "/images/projects/beloostrov/photo-10.jpg", "/images/projects/beloostrov/photo-11.jpg", "/images/projects/beloostrov/photo-2.jpg", "/images/projects/beloostrov/photo-3.jpg", "/images/projects/beloostrov/photo-4.jpg", "/images/projects/beloostrov/photo-5.jpg", "/images/projects/beloostrov/photo-6.jpg", "/images/projects/beloostrov/photo-7.jpg", "/images/projects/beloostrov/photo-8.jpg", "/images/projects/beloostrov/photo-9.jpg"],
    plans: [],
    slug: "beloostrov",
    tags: ["gazobeton"],
    description: "КОТЕЛЬНАЯ; ТЕРРАСА; КРЫЛЬЦО; КЛАДОВАЯ; ГАРДЕРОБНАЯ",
  },
  {
    id: 7,
    title: "Дом из клееного бруса (Булгаково Лайф)",
    nameOrig: "Булгаково Лайф",
    material: "Клееный брус",
    area: 140,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "5,4 млн ₽",
    image: "/images/projects/bulgakovo-lajf/photo-1.jpg",
    images: ["/images/projects/bulgakovo-lajf/photo-1.jpg", "/images/projects/bulgakovo-lajf/photo-2.jpg", "/images/projects/bulgakovo-lajf/photo-3.jpg", "/images/projects/bulgakovo-lajf/photo-4.jpg"],
    plans: ["/images/projects/bulgakovo-lajf/plan-1.jpg", "/images/projects/bulgakovo-lajf/plan-2.jpg"],
    slug: "bulgakovo-lajf",
    tags: ["brus"],
    description: "3 Террасы; Второй Свет; Балкон",
  },
  {
    id: 8,
    title: "Дом из газобетона (Вайя)",
    nameOrig: "Вайя",
    material: "Газобетон",
    area: 247,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "10,4 млн ₽",
    image: "/images/projects/vajya/photo-1.jpg",
    images: ["/images/projects/vajya/photo-1.jpg", "/images/projects/vajya/photo-2.jpg", "/images/projects/vajya/photo-3.jpg", "/images/projects/vajya/photo-4.jpg", "/images/projects/vajya/photo-5.jpg", "/images/projects/vajya/photo-6.jpg"],
    plans: ["/images/projects/vajya/plan-1.jpg", "/images/projects/vajya/plan-2.jpg"],
    slug: "vajya",
    tags: ["gazobeton"],
    description: "ГАРДЕРОБНАЯ; САУНА; ТЕРРАСА; КРЫЛЬЦО",
  },
  {
    id: 9,
    title: "Дом из газобетона (Володарский)",
    nameOrig: "Володарский",
    material: "Газобетон",
    area: 163,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7,3 млн ₽",
    image: "/images/projects/volodarskij/photo-1.jpg",
    images: ["/images/projects/volodarskij/photo-1.jpg", "/images/projects/volodarskij/photo-2.jpg", "/images/projects/volodarskij/photo-3.jpg", "/images/projects/volodarskij/photo-4.jpg"],
    plans: ["/images/projects/volodarskij/plan-1.jpg", "/images/projects/volodarskij/plan-2.jpg"],
    slug: "volodarskij",
    tags: ["gazobeton"],
    description: "ГАРДЕРОБНАЯ",
  },
  {
    id: 10,
    title: "Дом из газобетона (Вяхтелево)",
    nameOrig: "Вяхтелево",
    material: "Газобетон",
    area: 260,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "11,7 млн ₽",
    image: "/images/projects/vyahtelevo/photo-1.jpg",
    images: ["/images/projects/vyahtelevo/photo-1.jpg", "/images/projects/vyahtelevo/photo-2.jpg", "/images/projects/vyahtelevo/photo-3.jpg", "/images/projects/vyahtelevo/photo-4.jpg", "/images/projects/vyahtelevo/photo-5.jpg", "/images/projects/vyahtelevo/photo-6.jpg", "/images/projects/vyahtelevo/photo-7.jpg", "/images/projects/vyahtelevo/photo-8.jpg", "/images/projects/vyahtelevo/photo-9.jpg"],
    plans: ["/images/projects/vyahtelevo/plan-1.jpg"],
    slug: "vyahtelevo",
    tags: ["gazobeton"],
    description: "2 ГАРДЕРОБНЫХ; 2 КРЫЛЬЦА; ГАРАЖ; ТЕРРАСА; КЛАДОВАЯ; МИНИ-КОТЕЛЬНАЯ",
  },
  {
    id: 11,
    title: "Дом из газобетона (Вартемяги)",
    nameOrig: "Вартемяги",
    material: "Газобетон",
    area: 366,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "12,7 млн ₽",
    image: "/images/projects/vartemyagi/photo-1.jpg",
    images: ["/images/projects/vartemyagi/photo-1.jpg", "/images/projects/vartemyagi/photo-10.jpg", "/images/projects/vartemyagi/photo-11.jpg", "/images/projects/vartemyagi/photo-12.jpg", "/images/projects/vartemyagi/photo-2.jpg", "/images/projects/vartemyagi/photo-3.jpg", "/images/projects/vartemyagi/photo-4.jpg", "/images/projects/vartemyagi/photo-5.jpg", "/images/projects/vartemyagi/photo-6.jpg", "/images/projects/vartemyagi/photo-7.jpg", "/images/projects/vartemyagi/photo-8.jpg", "/images/projects/vartemyagi/photo-9.jpg"],
    plans: ["/images/projects/vartemyagi/plan-1.jpg", "/images/projects/vartemyagi/plan-2.jpg", "/images/projects/vartemyagi/plan-3.jpg"],
    slug: "vartemyagi",
    tags: ["gazobeton"],
    description: "Котельная; Кладовая; Бильярдная; Парная; Терраса; Балкон; Кабинет",
  },
  {
    id: 12,
    title: "Дом из газобетона (Васкелово)",
    nameOrig: "Васкелово",
    material: "Газобетон",
    area: 355,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "13,6 млн ₽",
    image: "/images/projects/vaskelovo/photo-1.jpg",
    images: ["/images/projects/vaskelovo/photo-1.jpg", "/images/projects/vaskelovo/photo-10.jpg", "/images/projects/vaskelovo/photo-11.jpg", "/images/projects/vaskelovo/photo-12.jpg", "/images/projects/vaskelovo/photo-13.jpg", "/images/projects/vaskelovo/photo-2.jpg", "/images/projects/vaskelovo/photo-3.jpg", "/images/projects/vaskelovo/photo-4.jpg", "/images/projects/vaskelovo/photo-5.jpeg", "/images/projects/vaskelovo/photo-6.jpeg", "/images/projects/vaskelovo/photo-7.jpeg", "/images/projects/vaskelovo/photo-8.jpg", "/images/projects/vaskelovo/photo-9.jpg"],
    plans: ["/images/projects/vaskelovo/plan-1.jpg"],
    slug: "vaskelovo",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Сауна; Гараж; Кабинет; Постирочная",
  },
  {
    id: 13,
    title: "Дом из кирпича (Ветеран 1)",
    nameOrig: "Ветеран 1",
    material: "Кирпич",
    area: 291,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "13,1 млн ₽",
    image: "/images/projects/veteran/photo-1.jpeg",
    images: ["/images/projects/veteran/photo-1.jpeg", "/images/projects/veteran/photo-2.jpeg", "/images/projects/veteran/photo-3.jpeg", "/images/projects/veteran/photo-4.jpeg", "/images/projects/veteran/photo-5.webp", "/images/projects/veteran/photo-6.webp", "/images/projects/veteran/photo-7.webp", "/images/projects/veteran/photo-8.webp", "/images/projects/veteran/photo-9.webp"],
    plans: ["/images/projects/veteran/plan-1.jpg", "/images/projects/veteran/plan-2.jpg"],
    slug: "veteran",
    tags: ["kirpich"],
    description: "Крыльцо; 4 Гардеробных; Котельная",
  },
  {
    id: 14,
    title: "Дом из кирпича (Ветеран 2)",
    nameOrig: "Ветеран 2",
    material: "Кирпич",
    area: 381,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "13,6 млн ₽",
    image: "/images/projects/veteran-2/photo-1.jpeg",
    images: ["/images/projects/veteran-2/photo-1.jpeg", "/images/projects/veteran-2/photo-2.jpeg", "/images/projects/veteran-2/photo-3.jpeg", "/images/projects/veteran-2/photo-4.jpeg", "/images/projects/veteran-2/photo-5.webp", "/images/projects/veteran-2/photo-6.webp", "/images/projects/veteran-2/photo-7.webp", "/images/projects/veteran-2/photo-8.webp"],
    plans: ["/images/projects/veteran-2/plan-1.jpg", "/images/projects/veteran-2/plan-2.jpg"],
    slug: "veteran-2",
    tags: ["kirpich"],
    description: "Терраса; Гардеробная; Камин; Котельная; 2 Крыльцв",
  },
  {
    id: 15,
    title: "Дом из газобетона (Ветеран 3)",
    nameOrig: "Ветеран 3",
    material: "Газобетон",
    area: 355,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "10,9 млн ₽",
    image: "/images/projects/veteran-3/photo-1.jpeg",
    images: ["/images/projects/veteran-3/photo-1.jpeg", "/images/projects/veteran-3/photo-2.jpeg", "/images/projects/veteran-3/photo-3.jpeg", "/images/projects/veteran-3/photo-4.jpeg", "/images/projects/veteran-3/photo-5.webp", "/images/projects/veteran-3/photo-6.webp", "/images/projects/veteran-3/photo-7.webp", "/images/projects/veteran-3/photo-8.webp"],
    plans: ["/images/projects/veteran-3/plan-1.jpg", "/images/projects/veteran-3/plan-2.jpg"],
    slug: "veteran-3",
    tags: ["gazobeton"],
    description: "Терраса; Гардеробная; Гараж; 2 Кладовых; Котельная",
  },
  {
    id: 16,
    title: "Дом из газобетона (Вишневая)",
    nameOrig: "Вишневая",
    material: "Газобетон",
    area: 186,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,9 млн ₽",
    image: "/images/projects/vishnevaya/photo-1.jpeg",
    images: ["/images/projects/vishnevaya/photo-1.jpeg", "/images/projects/vishnevaya/photo-10.jpg", "/images/projects/vishnevaya/photo-2.jpeg", "/images/projects/vishnevaya/photo-3.jpeg", "/images/projects/vishnevaya/photo-4.jpeg", "/images/projects/vishnevaya/photo-5.jpeg", "/images/projects/vishnevaya/photo-6.jpeg", "/images/projects/vishnevaya/photo-7.jpg", "/images/projects/vishnevaya/photo-8.jpg", "/images/projects/vishnevaya/photo-9.jpg"],
    plans: ["/images/projects/vishnevaya/plan-1.jpg", "/images/projects/vishnevaya/plan-2.jpg"],
    slug: "vishnevaya",
    tags: ["gazobeton"],
    description: "Котельная; Гараж; Терраса",
  },
  {
    id: 17,
    title: "Дом из газобетона (Выборг Залив)",
    nameOrig: "Выборг Залив",
    material: "Газобетон",
    area: 230,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "8,6 млн ₽",
    image: "/images/projects/vyborg-zaliv/photo-1.jpeg",
    images: ["/images/projects/vyborg-zaliv/photo-1.jpeg", "/images/projects/vyborg-zaliv/photo-10.jpg", "/images/projects/vyborg-zaliv/photo-11.jpg", "/images/projects/vyborg-zaliv/photo-2.jpeg", "/images/projects/vyborg-zaliv/photo-3.jpeg", "/images/projects/vyborg-zaliv/photo-4.jpeg", "/images/projects/vyborg-zaliv/photo-5.jpeg", "/images/projects/vyborg-zaliv/photo-6.jpeg", "/images/projects/vyborg-zaliv/photo-7.jpeg", "/images/projects/vyborg-zaliv/photo-8.jpg", "/images/projects/vyborg-zaliv/photo-9.jpg"],
    plans: ["/images/projects/vyborg-zaliv/plan-1.jpg"],
    slug: "vyborg-zaliv",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Сауна; Терраса; Летняя кухня; Кладовая",
  },
  {
    id: 18,
    title: "Дом из керамоблоков (Вяземские Сады)",
    nameOrig: "Вяземские Сады",
    material: "Керамоблок",
    area: 234,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "10,4 млн ₽",
    image: "/images/projects/romanovo-lajf/photo-1.jpeg",
    images: ["/images/projects/romanovo-lajf/photo-1.jpeg", "/images/projects/romanovo-lajf/photo-2.jpeg", "/images/projects/romanovo-lajf/photo-3.jpeg", "/images/projects/romanovo-lajf/photo-4.jpeg"],
    plans: ["/images/projects/romanovo-lajf/plan-1.jpg", "/images/projects/romanovo-lajf/plan-2.jpg", "/images/projects/romanovo-lajf/plan-3.jpg"],
    slug: "romanovo-lajf",
    tags: ["keramoblok"],
    description: "Подвал; Котельная; Гараж; Веранда; Терраса",
  },
  {
    id: 19,
    title: "Дом из газобетона (Горки)",
    nameOrig: "Горки",
    material: "Газобетон",
    area: 158,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "6 млн ₽",
    image: "/images/projects/gorki/photo-1.jpeg",
    images: ["/images/projects/gorki/photo-1.jpeg", "/images/projects/gorki/photo-2.jpeg", "/images/projects/gorki/photo-3.jpeg", "/images/projects/gorki/photo-4.jpeg", "/images/projects/gorki/photo-5.jpeg", "/images/projects/gorki/photo-6.jpeg", "/images/projects/gorki/photo-7.jpg", "/images/projects/gorki/photo-8.jpg"],
    plans: ["/images/projects/gorki/plan-1.jpg", "/images/projects/gorki/plan-2.jpg"],
    slug: "gorki",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Сауна; Зимний сад; Терраса",
  },
  {
    id: 20,
    title: "Дом из газобетона (Дубки)",
    nameOrig: "Дубки",
    material: "Газобетон",
    area: 199,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "10,8 млн ₽",
    image: "/images/projects/dubki/photo-1.jpeg",
    images: ["/images/projects/dubki/photo-1.jpeg", "/images/projects/dubki/photo-2.jpeg", "/images/projects/dubki/photo-3.jpeg", "/images/projects/dubki/photo-4.jpeg", "/images/projects/dubki/photo-5.jpeg", "/images/projects/dubki/photo-6.jpeg"],
    plans: [],
    slug: "dubki",
    tags: ["gazobeton"],
    description: "КРЫЛЬЦО; ТЕРРАСА; ГАРДЕРОБНАЯ; ПОСТИРОЧНАЯ; ГАРАЖ; КОТЕЛЬНАЯ",
  },
  {
    id: 21,
    title: "Дом из газобетона (Дачная)",
    nameOrig: "Дачная",
    material: "Газобетон",
    area: 212,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,1 млн ₽",
    image: "/images/projects/dachnaya/photo-1.jpg",
    images: ["/images/projects/dachnaya/photo-1.jpg", "/images/projects/dachnaya/photo-2.jpg", "/images/projects/dachnaya/photo-3.jpg", "/images/projects/dachnaya/photo-4.jpg", "/images/projects/dachnaya/photo-5.jpg", "/images/projects/dachnaya/photo-6.jpg"],
    plans: ["/images/projects/dachnaya/plan-1.jpg", "/images/projects/dachnaya/plan-2.jpg"],
    slug: "dachnaya",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Сауна; Второй свет; Гараж; Кабинет",
  },
  {
    id: 22,
    title: "Дом из клееного бруса (Дворищи)",
    nameOrig: "Дворищи",
    material: "Клееный брус",
    area: 172,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,4 млн ₽",
    image: "/images/projects/dvorishhi/photo-1.jpeg",
    images: ["/images/projects/dvorishhi/photo-1.jpeg", "/images/projects/dvorishhi/photo-2.jpeg", "/images/projects/dvorishhi/photo-3.jpeg", "/images/projects/dvorishhi/photo-4.jpeg", "/images/projects/dvorishhi/photo-5.webp", "/images/projects/dvorishhi/photo-6.webp", "/images/projects/dvorishhi/photo-7.webp", "/images/projects/dvorishhi/photo-8.webp", "/images/projects/dvorishhi/photo-9.webp"],
    plans: ["/images/projects/dvorishhi/plan-1.jpg", "/images/projects/dvorishhi/plan-2.jpg"],
    slug: "dvorishhi",
    tags: ["brus"],
    description: "Терраса; Эркер; Гардеробная; Второй Свет",
  },
  {
    id: 23,
    title: "Дом из газобетона (Домодедово)",
    nameOrig: "Домодедово",
    material: "Газобетон",
    area: 254,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "10 млн ₽",
    image: "/images/projects/domodedovo/photo-1.jpeg",
    images: ["/images/projects/domodedovo/photo-1.jpeg", "/images/projects/domodedovo/photo-2.jpeg", "/images/projects/domodedovo/photo-3.jpeg", "/images/projects/domodedovo/photo-4.jpeg", "/images/projects/domodedovo/photo-5.jpg", "/images/projects/domodedovo/photo-6.jpg", "/images/projects/domodedovo/photo-7.jpg"],
    plans: ["/images/projects/domodedovo/plan-1.jpg", "/images/projects/domodedovo/plan-2.jpg"],
    slug: "domodedovo",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Гараж; Мастерская; Терраса; Крыльцо",
  },
  {
    id: 24,
    title: "Дом из клееного бруса (Дубровка 3)",
    nameOrig: "Дубровка 3",
    material: "Клееный брус",
    area: 187,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "10,1 млн ₽",
    image: "/images/projects/dubrovka-3/photo-1.jpeg",
    images: ["/images/projects/dubrovka-3/photo-1.jpeg", "/images/projects/dubrovka-3/photo-2.jpeg", "/images/projects/dubrovka-3/photo-3.jpeg", "/images/projects/dubrovka-3/photo-4.jpeg", "/images/projects/dubrovka-3/photo-5.jpg", "/images/projects/dubrovka-3/photo-6.jpg"],
    plans: ["/images/projects/dubrovka-3/plan-1.jpg", "/images/projects/dubrovka-3/plan-2.jpg"],
    slug: "dubrovka-3",
    tags: ["brus"],
    description: "2 Гардеробных; Крыльцо; Балкон; Котельная; Терраса",
  },
  {
    id: 25,
    title: "Дом из газобетона (Дубровка Московская)",
    nameOrig: "Дубровка Московская",
    material: "Газобетон",
    area: 189,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,6 млн ₽",
    image: "/images/projects/dybrovka-moskovskaya/photo-1.jpg",
    images: ["/images/projects/dybrovka-moskovskaya/photo-1.jpg", "/images/projects/dybrovka-moskovskaya/photo-2.jpg", "/images/projects/dybrovka-moskovskaya/photo-3.jpg", "/images/projects/dybrovka-moskovskaya/photo-4.jpg", "/images/projects/dybrovka-moskovskaya/photo-5.jpg", "/images/projects/dybrovka-moskovskaya/photo-6.jpg", "/images/projects/dybrovka-moskovskaya/photo-7.jpg"],
    plans: ["/images/projects/dybrovka-moskovskaya/plan-1.jpg", "/images/projects/dybrovka-moskovskaya/plan-2.jpg"],
    slug: "dybrovka-moskovskaya",
    tags: ["gazobeton"],
    description: "Котельная; Балкон; Терраса; Гардероб",
  },
  {
    id: 26,
    title: "Дом из газобетона (Дубровка Средняя)",
    nameOrig: "Дубровка Средняя",
    material: "Газобетон",
    area: 178,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "6,4 млн ₽",
    image: "/images/projects/dybrovka-srednya/photo-1.jpg",
    images: ["/images/projects/dybrovka-srednya/photo-1.jpg", "/images/projects/dybrovka-srednya/photo-2.jpg", "/images/projects/dybrovka-srednya/photo-3.jpg", "/images/projects/dybrovka-srednya/photo-4.jpg"],
    plans: ["/images/projects/dybrovka-srednya/plan-1.jpg", "/images/projects/dybrovka-srednya/plan-2.jpg"],
    slug: "dybrovka-srednya",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Терраса",
  },
  {
    id: 27,
    title: "Дом из газобетона (Дунай)",
    nameOrig: "Дунай",
    material: "Газобетон",
    area: 134,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "5,1 млн ₽",
    image: "/images/projects/dunay/photo-1.jpeg",
    images: ["/images/projects/dunay/photo-1.jpeg", "/images/projects/dunay/photo-2.jpeg", "/images/projects/dunay/photo-3.jpeg", "/images/projects/dunay/photo-4.jpeg", "/images/projects/dunay/photo-5.jpeg", "/images/projects/dunay/photo-6.jpeg", "/images/projects/dunay/photo-7.jpg", "/images/projects/dunay/photo-8.jpg", "/images/projects/dunay/photo-9.jpg"],
    plans: ["/images/projects/dunay/plan-1.jpg", "/images/projects/dunay/plan-2.jpg"],
    slug: "dunay",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Терраса",
  },
  {
    id: 28,
    title: "Дом из газобетона (Елизаветино)",
    nameOrig: "Елизаветино",
    material: "Газобетон",
    area: 160,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "8 млн ₽",
    image: "/images/projects/elizavetino/photo-1.jpg",
    images: ["/images/projects/elizavetino/photo-1.jpg", "/images/projects/elizavetino/photo-2.jpg", "/images/projects/elizavetino/photo-3.jpg", "/images/projects/elizavetino/photo-4.jpg"],
    plans: ["/images/projects/elizavetino/plan-1.jpg"],
    slug: "elizavetino",
    tags: ["gazobeton"],
    description: "БОЙЛЕРНАЯ; ТЕРРАСА; КРЫЛЬЦО",
  },
  {
    id: 29,
    title: "Дом из клееного бруса (Елизарово)",
    nameOrig: "Елизарово",
    material: "Клееный брус",
    area: 136,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6 млн ₽",
    image: "/images/projects/elizarovo/photo-1.jpeg",
    images: ["/images/projects/elizarovo/photo-1.jpeg", "/images/projects/elizarovo/photo-2.jpeg", "/images/projects/elizarovo/photo-3.jpeg", "/images/projects/elizarovo/photo-4.jpg"],
    plans: ["/images/projects/elizarovo/plan-1.jpg"],
    slug: "elizarovo",
    tags: ["brus"],
    description: "Терраса; Котельная; Гардеробная",
  },
  {
    id: 30,
    title: "Дом из газобетона (Зеленоградск)",
    nameOrig: "Зеленоградск",
    material: "Газобетон",
    area: 2182,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "10,5 млн ₽",
    image: "/images/projects/zelenogradsk/photo-1.jpg",
    images: ["/images/projects/zelenogradsk/photo-1.jpg", "/images/projects/zelenogradsk/photo-2.jpg", "/images/projects/zelenogradsk/photo-3.jpg", "/images/projects/zelenogradsk/photo-4.jpg"],
    plans: ["/images/projects/zelenogradsk/plan-1.jpg", "/images/projects/zelenogradsk/plan-2.jpg"],
    slug: "zelenogradsk",
    tags: ["gazobeton"],
    description: "3 ГАРДЕРОБНЫХ; ВЕРАНДА; ЗИМНИЙ САД; ПОСТИРОЧНАЯ; КОТЕЛЬНАЯ; КЛАДОВАЯ",
  },
  {
    id: 31,
    title: "Дом из газобетона (Зеленый 2)",
    nameOrig: "Зеленый 2",
    material: "Газобетон",
    area: 307,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "14,2 млн ₽",
    image: "/images/projects/zelenyj-2/photo-1.jpg",
    images: ["/images/projects/zelenyj-2/photo-1.jpg", "/images/projects/zelenyj-2/photo-2.jpg", "/images/projects/zelenyj-2/photo-3.jpg", "/images/projects/zelenyj-2/photo-4.jpg"],
    plans: ["/images/projects/zelenyj-2/plan-1.jpg", "/images/projects/zelenyj-2/plan-2.jpg"],
    slug: "zelenyj-2",
    tags: ["gazobeton"],
    description: "КОТЕЛЬНАЯ; КРЫЛЬЦО; ГАРДЕРОБНАЯ; БАЛКОН",
  },
  {
    id: 32,
    title: "Дом из газобетона (Заозерное)",
    nameOrig: "Заозерное",
    material: "Газобетон",
    area: 164,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6,9 млн ₽",
    image: "/images/projects/zaozernoe/photo-1.jpg",
    images: ["/images/projects/zaozernoe/photo-1.jpg", "/images/projects/zaozernoe/photo-2.jpg", "/images/projects/zaozernoe/photo-3.jpg", "/images/projects/zaozernoe/photo-4.jpg", "/images/projects/zaozernoe/photo-5.jpg", "/images/projects/zaozernoe/photo-6.jpg", "/images/projects/zaozernoe/photo-7.jpg"],
    plans: ["/images/projects/zaozernoe/plan-1.jpg"],
    slug: "zaozernoe",
    tags: ["gazobeton"],
    description: "Котельная; Терраса; Гардеробная; Кладовая; Гараж",
  },
  {
    id: 33,
    title: "Дом из клееного бруса (Земляничный)",
    nameOrig: "Земляничный",
    material: "Клееный брус",
    area: 166,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7 млн ₽",
    image: "/images/projects/zemlyanichnyj/photo-1.jpg",
    images: ["/images/projects/zemlyanichnyj/photo-1.jpg", "/images/projects/zemlyanichnyj/photo-2.jpg", "/images/projects/zemlyanichnyj/photo-3.jpg", "/images/projects/zemlyanichnyj/photo-4.jpg"],
    plans: ["/images/projects/zemlyanichnyj/plan-1.jpg", "/images/projects/zemlyanichnyj/plan-2.jpg"],
    slug: "zemlyanichnyj",
    tags: ["brus"],
    description: "Терраса; Гардеробная; Второй Свет",
  },
  {
    id: 34,
    title: "Дом из клееного бруса (Зимний Сад)",
    nameOrig: "Зимний Сад",
    material: "Клееный брус",
    area: 157,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6,7 млн ₽",
    image: "/images/projects/zimnij-sad/photo-1.jpeg",
    images: ["/images/projects/zimnij-sad/photo-1.jpeg", "/images/projects/zimnij-sad/photo-2.jpeg", "/images/projects/zimnij-sad/photo-3.jpeg", "/images/projects/zimnij-sad/photo-4.jpeg", "/images/projects/zimnij-sad/photo-5.jpeg"],
    plans: [],
    slug: "zimnij-sad",
    tags: ["brus"],
    description: "Террасы; Котельная; Крыльцо; Сауна/Хаммам",
  },
  {
    id: 35,
    title: "Дом из клееного бруса (Искра)",
    nameOrig: "Искра",
    material: "Клееный брус",
    area: 204,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,4 млн ₽",
    image: "/images/projects/iskra/photo-1.jpg",
    images: ["/images/projects/iskra/photo-1.jpg", "/images/projects/iskra/photo-2.jpg", "/images/projects/iskra/photo-3.jpg", "/images/projects/iskra/photo-4.jpg"],
    plans: ["/images/projects/iskra/plan-1.jpg", "/images/projects/iskra/plan-2.jpg"],
    slug: "iskra",
    tags: ["brus"],
    description: "3 Террасы; Гардеробная; Котельная; Балкон; Второй Свет; Эркер",
  },
  {
    id: 36,
    title: "Дом из газобетона (Ишино)",
    nameOrig: "Ишино",
    material: "Газобетон",
    area: 273,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "10,5 млн ₽",
    image: "/images/projects/ishino/photo-1.jpeg",
    images: ["/images/projects/ishino/photo-1.jpeg", "/images/projects/ishino/photo-2.jpeg", "/images/projects/ishino/photo-3.jpeg", "/images/projects/ishino/photo-4.jpeg", "/images/projects/ishino/photo-5.webp", "/images/projects/ishino/photo-6.webp", "/images/projects/ishino/photo-7.webp", "/images/projects/ishino/photo-8.webp"],
    plans: ["/images/projects/ishino/plan-1.jpg", "/images/projects/ishino/plan-2.jpg"],
    slug: "ishino",
    tags: ["gazobeton"],
    description: "Камин; Котельная; Веранда; Эркер; Кладовая; 3 Балкона",
  },
  {
    id: 37,
    title: "Дом из газобетона (Коркино)",
    nameOrig: "Коркино",
    material: "Газобетон",
    area: 156,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7,1 млн ₽",
    image: "/images/projects/korkino/photo-1.jpg",
    images: ["/images/projects/korkino/photo-1.jpg", "/images/projects/korkino/photo-2.jpg", "/images/projects/korkino/photo-3.jpg", "/images/projects/korkino/photo-4.jpg"],
    plans: ["/images/projects/korkino/plan-1.jpg", "/images/projects/korkino/plan-2.jpg"],
    slug: "korkino",
    tags: ["gazobeton"],
    description: "2 ГАРДЕРОБНЫХ; КОТЕЛЬНАЯ; КРЫЛЬЦО",
  },
  {
    id: 38,
    title: "Дом из газобетона (Коркинский)",
    nameOrig: "Коркинский",
    material: "Газобетон",
    area: 136,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6,6 млн ₽",
    image: "/images/projects/korkinskij/photo-1.jpg",
    images: ["/images/projects/korkinskij/photo-1.jpg", "/images/projects/korkinskij/photo-10.jpg", "/images/projects/korkinskij/photo-2.jpg", "/images/projects/korkinskij/photo-3.jpg", "/images/projects/korkinskij/photo-4.jpg", "/images/projects/korkinskij/photo-5.jpg", "/images/projects/korkinskij/photo-6.jpg", "/images/projects/korkinskij/photo-7.jpg", "/images/projects/korkinskij/photo-8.jpg", "/images/projects/korkinskij/photo-9.jpg"],
    plans: ["/images/projects/korkinskij/plan-1.jpg", "/images/projects/korkinskij/plan-2.jpg"],
    slug: "korkinskij",
    tags: ["gazobeton"],
    description: "КОТЕЛЬНАЯ; КРЫЛЬЦО; ГАРДЕРОБНАЯ",
  },
  {
    id: 39,
    title: "Дом из газобетона (Коробово)",
    nameOrig: "Коробово",
    material: "Газобетон",
    area: 443,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "16,4 млн ₽",
    image: "/images/projects/korobovo/photo-1.jpg",
    images: ["/images/projects/korobovo/photo-1.jpg", "/images/projects/korobovo/photo-2.jpg", "/images/projects/korobovo/photo-3.jpg", "/images/projects/korobovo/photo-4.jpg", "/images/projects/korobovo/photo-5.jpg", "/images/projects/korobovo/photo-6.jpg"],
    plans: ["/images/projects/korobovo/plan-1.jpg", "/images/projects/korobovo/plan-2.jpg"],
    slug: "korobovo",
    tags: ["gazobeton"],
    description: "2 КЛАДОВЫХ; 4 ГАРДЕРОБНЫХ; ТЕХ. ПОМЕЩЕНИЕ; ПРАЧЕЧНАЯ; ГАРАЖ",
  },
  {
    id: 40,
    title: "Дом из газобетона (Корфу)",
    nameOrig: "Корфу",
    material: "Газобетон",
    area: 197,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,2 млн ₽",
    image: "/images/projects/korfu/photo-1.jpg",
    images: ["/images/projects/korfu/photo-1.jpg", "/images/projects/korfu/photo-2.jpg", "/images/projects/korfu/photo-3.jpg", "/images/projects/korfu/photo-4.jpg", "/images/projects/korfu/photo-5.jpg", "/images/projects/korfu/photo-6.jpg", "/images/projects/korfu/photo-7.jpg"],
    plans: ["/images/projects/korfu/plan-1.jpg", "/images/projects/korfu/plan-2.jpg"],
    slug: "korfu",
    tags: ["gazobeton"],
    description: "Гараж; Мини-котельная; Гардеробная; Лоджия",
  },
  {
    id: 41,
    title: "Дом из керамоблоков (Ландышевка)",
    nameOrig: "Ландышевка",
    material: "Керамоблок",
    area: 279,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5,8 млн ₽",
    image: "/images/projects/landyshevka/photo-1.jpg",
    images: ["/images/projects/landyshevka/photo-1.jpg", "/images/projects/landyshevka/photo-2.jpg", "/images/projects/landyshevka/photo-3.jpg", "/images/projects/landyshevka/photo-4.jpg", "/images/projects/landyshevka/photo-5.jpg", "/images/projects/landyshevka/photo-6.jpg", "/images/projects/landyshevka/photo-7.jpg", "/images/projects/landyshevka/photo-8.jpg", "/images/projects/landyshevka/photo-9.jpg"],
    plans: ["/images/projects/landyshevka/plan-1.jpg", "/images/projects/landyshevka/plan-2.jpg", "/images/projects/landyshevka/plan-3.jpg"],
    slug: "landyshevka",
    tags: ["keramoblok"],
    description: "2 ГАРДЕРОБНЫХ; 2 БАЛКОНА; ТЕРРАСА; КАБИНЕТ; КОТЕЛЬНАЯ; КРЫЛЬЦО",
  },
  {
    id: 42,
    title: "Дом из газобетона (Лосиный Парк)",
    nameOrig: "Лосиный Парк",
    material: "Газобетон",
    area: 177,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "6,7 млн ₽",
    image: "/images/projects/losinuy-park/photo-1.jpeg",
    images: ["/images/projects/losinuy-park/photo-1.jpeg", "/images/projects/losinuy-park/photo-2.jpeg", "/images/projects/losinuy-park/photo-3.jpeg", "/images/projects/losinuy-park/photo-4.jpeg", "/images/projects/losinuy-park/photo-5.jpg", "/images/projects/losinuy-park/photo-6.webp"],
    plans: ["/images/projects/losinuy-park/plan-1.jpg", "/images/projects/losinuy-park/plan-2.jpg"],
    slug: "losinuy-park",
    tags: ["gazobeton"],
    description: "Котельная; Терраса; Крыльцо",
  },
  {
    id: 43,
    title: "Дом из керамоблоков (Малое Репино)",
    nameOrig: "Малое Репино",
    material: "Керамоблок",
    area: 363,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "15,2 млн ₽",
    image: "/images/projects/maloe-repino/photo-1.jpg",
    images: ["/images/projects/maloe-repino/photo-1.jpg", "/images/projects/maloe-repino/photo-2.jpg", "/images/projects/maloe-repino/photo-3.jpg", "/images/projects/maloe-repino/photo-4.jpg", "/images/projects/maloe-repino/photo-5.jpg"],
    plans: ["/images/projects/maloe-repino/plan-1.jpg", "/images/projects/maloe-repino/plan-2.jpg"],
    slug: "maloe-repino",
    tags: ["keramoblok"],
    description: "КРЫЛЬЦО; КАБИНЕТ; ПАРНАЯ; ГАРДЕРОБНАЯ; ЗОНА СПА; ХАМАМ; КОМНАТА ДЛЯ СПОРТА; ПОСТИРОЧНАЯ; ГАРАЖ; КОТЕЛЬНАЯ",
  },
  {
    id: 44,
    title: "Дом из газобетона (Марфино)",
    nameOrig: "Марфино",
    material: "Газобетон",
    area: 112,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5,2 млн ₽",
    image: "/images/projects/marfino/photo-1.jpg",
    images: ["/images/projects/marfino/photo-1.jpg", "/images/projects/marfino/photo-2.jpg", "/images/projects/marfino/photo-3.jpeg", "/images/projects/marfino/photo-4.jpg", "/images/projects/marfino/photo-5.jpg"],
    plans: [],
    slug: "marfino",
    tags: ["gazobeton"],
    description: "КОТЕЛЬНАЯ; ПОСТИРОЧНАЯ; КРЫЛЬЦО; ГАРДЕРОБНАЯ",
  },
  {
    id: 45,
    title: "Дом из газобетона (Микеа)",
    nameOrig: "Микеа",
    material: "Газобетон",
    area: 220,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "9,9 млн ₽",
    image: "/images/projects/mikea/photo-1.jpg",
    images: ["/images/projects/mikea/photo-1.jpg", "/images/projects/mikea/photo-2.jpg", "/images/projects/mikea/photo-3.jpg", "/images/projects/mikea/photo-4.jpg"],
    plans: ["/images/projects/mikea/plan-1.jpg"],
    slug: "mikea",
    tags: ["gazobeton"],
    description: "ПОСТИРОЧНАЯ; КОТЕЛЬНАЯ; КРЫЛЬЦО; ТЕРРАСА",
  },
  {
    id: 46,
    title: "Дом из газобетона (Мишино)",
    nameOrig: "Мишино",
    material: "Газобетон",
    area: 272,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "15,6 млн ₽",
    image: "/images/projects/mishino/photo-1.jpg",
    images: ["/images/projects/mishino/photo-1.jpg", "/images/projects/mishino/photo-2.jpg", "/images/projects/mishino/photo-3.jpg", "/images/projects/mishino/photo-4.jpg"],
    plans: ["/images/projects/mishino/plan-1.jpg", "/images/projects/mishino/plan-2.jpg"],
    slug: "mishino",
    tags: ["gazobeton"],
    description: "3 БАЛКОНА; 2 КРЫЛЬЦА; САУНА; КЛАДОВАЯ; ТЕРРАСА; КОТЕЛЬНАЯ",
  },
  {
    id: 47,
    title: "Дом из клееного бруса (Малинки Лайф)",
    nameOrig: "Малинки Лайф",
    material: "Клееный брус",
    area: 177,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,2 млн ₽",
    image: "/images/projects/malinki-lajf/photo-1.jpg",
    images: ["/images/projects/malinki-lajf/photo-1.jpg", "/images/projects/malinki-lajf/photo-2.jpg", "/images/projects/malinki-lajf/photo-3.jpg", "/images/projects/malinki-lajf/photo-4.jpg", "/images/projects/malinki-lajf/photo-5.jpg", "/images/projects/malinki-lajf/photo-6.jpg", "/images/projects/malinki-lajf/photo-7.jpg", "/images/projects/malinki-lajf/photo-8.jpg"],
    plans: ["/images/projects/malinki-lajf/plan-1.jpg", "/images/projects/malinki-lajf/plan-2.jpg"],
    slug: "malinki-lajf",
    tags: ["brus"],
    description: "Терраса; Гардеробная; Котельная",
  },
  {
    id: 48,
    title: "Дом из газобетона (Малиновая-Зеленая)",
    nameOrig: "Малиновая-Зеленая",
    material: "Газобетон",
    area: 254,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,3 млн ₽",
    image: "/images/projects/malinovaya/photo-1.jpg",
    images: ["/images/projects/malinovaya/photo-1.jpg", "/images/projects/malinovaya/photo-2.jpg", "/images/projects/malinovaya/photo-3.jpg", "/images/projects/malinovaya/photo-4.jpg", "/images/projects/malinovaya/photo-5.jpg", "/images/projects/malinovaya/photo-6.jpg", "/images/projects/malinovaya/photo-7.jpg", "/images/projects/malinovaya/photo-8.jpg", "/images/projects/malinovaya/photo-9.jpg"],
    plans: ["/images/projects/malinovaya/plan-1.jpg", "/images/projects/malinovaya/plan-2.jpg"],
    slug: "malinovaya",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Коридор с лестницей; Гараж; Терраса",
  },
  {
    id: 49,
    title: "Дом из газобетона (Малые Бережки)",
    nameOrig: "Малые Бережки",
    material: "Газобетон",
    area: 439,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "15,3 млн ₽",
    image: "/images/projects/malye-berezhki/photo-1.jpeg",
    images: ["/images/projects/malye-berezhki/photo-1.jpeg", "/images/projects/malye-berezhki/photo-2.jpeg", "/images/projects/malye-berezhki/photo-3.jpeg", "/images/projects/malye-berezhki/photo-4.jpeg", "/images/projects/malye-berezhki/photo-5.webp", "/images/projects/malye-berezhki/photo-6.webp", "/images/projects/malye-berezhki/photo-7.webp"],
    plans: ["/images/projects/malye-berezhki/plan-1.jpg", "/images/projects/malye-berezhki/plan-2.jpg"],
    slug: "malye-berezhki",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Сауна; Кабинет; Терраса",
  },
  {
    id: 50,
    title: "Дом из газобетона (Медное)",
    nameOrig: "Медное",
    material: "Газобетон",
    area: 214,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "9,8 млн ₽",
    image: "/images/projects/mednoe/photo-1.jpg",
    images: ["/images/projects/mednoe/photo-1.jpg", "/images/projects/mednoe/photo-10.jpg", "/images/projects/mednoe/photo-11.jpg", "/images/projects/mednoe/photo-2.jpg", "/images/projects/mednoe/photo-3.jpg", "/images/projects/mednoe/photo-4.jpg", "/images/projects/mednoe/photo-5.jpg", "/images/projects/mednoe/photo-6.jpg", "/images/projects/mednoe/photo-7.jpg", "/images/projects/mednoe/photo-8.jpg", "/images/projects/mednoe/photo-9.jpg"],
    plans: ["/images/projects/mednoe/plan-1.jpg"],
    slug: "mednoe",
    tags: ["gazobeton"],
    description: "Котельная; 2 Гардеробные; Сауна; Терраса; Кладовая; Кабинет",
  },
  {
    id: 51,
    title: "Дом из клееного бруса (Мичуринец)",
    nameOrig: "Мичуринец",
    material: "Клееный брус",
    area: 180,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,4 млн ₽",
    image: "/images/projects/michurinecz/photo-1.jpg",
    images: ["/images/projects/michurinecz/photo-1.jpg", "/images/projects/michurinecz/photo-2.jpg", "/images/projects/michurinecz/photo-3.jpg", "/images/projects/michurinecz/photo-4.jpg"],
    plans: ["/images/projects/michurinecz/plan-1.jpg", "/images/projects/michurinecz/plan-2.jpg"],
    slug: "michurinecz",
    tags: ["brus"],
    description: "Терраса; Эркер; Котельная; Гардеробная; Второй Свет",
  },
  {
    id: 52,
    title: "Дом из газобетона (Нурми Хилс)",
    nameOrig: "Нурми Хилс",
    material: "Газобетон",
    area: 253,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "10,9 млн ₽",
    image: "/images/projects/nurmi-hils/photo-1.jpg",
    images: ["/images/projects/nurmi-hils/photo-1.jpg", "/images/projects/nurmi-hils/photo-10.jpg", "/images/projects/nurmi-hils/photo-11.jpg", "/images/projects/nurmi-hils/photo-12.jpg", "/images/projects/nurmi-hils/photo-13.jpg", "/images/projects/nurmi-hils/photo-14.jpg", "/images/projects/nurmi-hils/photo-15.jpg", "/images/projects/nurmi-hils/photo-16.jpg", "/images/projects/nurmi-hils/photo-17.jpg", "/images/projects/nurmi-hils/photo-2.jpg", "/images/projects/nurmi-hils/photo-3.jpg", "/images/projects/nurmi-hils/photo-4.jpg", "/images/projects/nurmi-hils/photo-5.jpg", "/images/projects/nurmi-hils/photo-6.jpg", "/images/projects/nurmi-hils/photo-7.jpg", "/images/projects/nurmi-hils/photo-8.jpg", "/images/projects/nurmi-hils/photo-9.jpg"],
    plans: ["/images/projects/nurmi-hils/plan-1.jpg", "/images/projects/nurmi-hils/plan-2.jpg"],
    slug: "nurmi-hils",
    tags: ["gazobeton"],
    description: "2 ГАРДЕРОБНЫЕ; КОТЕЛЬНАЯ; КЛАДОВАЯ; ПОСТИРОЧНАЯ; КРЫЛЬЦО; ТЕРРАСА",
  },
  {
    id: 53,
    title: "Дом из клееного бруса (Нагорье)",
    nameOrig: "Нагорье",
    material: "Клееный брус",
    area: 236,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,2 млн ₽",
    image: "/images/projects/nagore/photo-1.jpg",
    images: ["/images/projects/nagore/photo-1.jpg", "/images/projects/nagore/photo-2.jpg", "/images/projects/nagore/photo-3.jpg", "/images/projects/nagore/photo-4.jpg"],
    plans: ["/images/projects/nagore/plan-1.jpg", "/images/projects/nagore/plan-2.jpg"],
    slug: "nagore",
    tags: ["brus"],
    description: "Терраса; Котельная; Гардеробная; Балкон",
  },
  {
    id: 54,
    title: "Дом из газобетона (Нурми Мини)",
    nameOrig: "Нурми Мини",
    material: "Газобетон",
    area: 108,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "4,8 млн ₽",
    image: "/images/projects/nurmimini/photo-1.jpg",
    images: ["/images/projects/nurmimini/photo-1.jpg", "/images/projects/nurmimini/photo-10.jpg", "/images/projects/nurmimini/photo-11.jpg", "/images/projects/nurmimini/photo-12.jpg", "/images/projects/nurmimini/photo-13.jpg", "/images/projects/nurmimini/photo-14.jpg", "/images/projects/nurmimini/photo-2.jpg", "/images/projects/nurmimini/photo-3.jpg", "/images/projects/nurmimini/photo-4.jpg", "/images/projects/nurmimini/photo-5.jpg", "/images/projects/nurmimini/photo-6.jpg", "/images/projects/nurmimini/photo-7.jpg", "/images/projects/nurmimini/photo-8.jpg", "/images/projects/nurmimini/photo-9.jpg"],
    plans: ["/images/projects/nurmimini/plan-1.jpg"],
    slug: "nurmimini",
    tags: ["gazobeton"],
    description: "Кухня-гостиная; Терраса; Кладовая",
  },
  {
    id: 55,
    title: "Дом из керамоблоков (Онегино 1)",
    nameOrig: "Онегино 1",
    material: "Керамоблок",
    area: 1127,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "56,2 млн ₽",
    image: "/images/projects/onegino-1/photo-1.jpg",
    images: ["/images/projects/onegino-1/photo-1.jpg", "/images/projects/onegino-1/photo-10.jpg", "/images/projects/onegino-1/photo-11.jpg", "/images/projects/onegino-1/photo-12.jpg", "/images/projects/onegino-1/photo-13.jpg", "/images/projects/onegino-1/photo-14.jpg", "/images/projects/onegino-1/photo-15.jpg", "/images/projects/onegino-1/photo-16.jpg", "/images/projects/onegino-1/photo-17.jpg", "/images/projects/onegino-1/photo-18.jpg", "/images/projects/onegino-1/photo-19.jpg", "/images/projects/onegino-1/photo-2.jpg", "/images/projects/onegino-1/photo-20.jpg", "/images/projects/onegino-1/photo-21.jpg", "/images/projects/onegino-1/photo-22.jpg", "/images/projects/onegino-1/photo-23.jpg", "/images/projects/onegino-1/photo-3.jpg", "/images/projects/onegino-1/photo-4.jpg", "/images/projects/onegino-1/photo-5.jpg", "/images/projects/onegino-1/photo-6.jpg", "/images/projects/onegino-1/photo-7.jpg", "/images/projects/onegino-1/photo-8.jpg", "/images/projects/onegino-1/photo-9.jpg"],
    plans: ["/images/projects/onegino-1/plan-1.jpg", "/images/projects/onegino-1/plan-2.jpg", "/images/projects/onegino-1/plan-3.jpg", "/images/projects/onegino-1/plan-4.jpg", "/images/projects/onegino-1/plan-5.jpg"],
    slug: "onegino-1",
    tags: ["keramoblok"],
    description: "6 ГАРДЕРОБНЫХ; 2 КЛАДОВЫХ; 3 ТЕРРАСЫ; КРЫЛЬЦО; БАССЕЙН; ХАМАМ; ТРЕНАЖЕРНЫЙ ЗАЛ; ПОСТИРОЧНАЯ; КАБИНЕТ; БИЛЬЯРДНАЯ",
  },
  {
    id: 56,
    title: "Дом из газобетона (Охтинское)",
    nameOrig: "Охтинское",
    material: "Газобетон",
    area: 481,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "22,6 млн ₽",
    image: "/images/projects/ohtinskoe/photo-1.jpg",
    images: ["/images/projects/ohtinskoe/photo-1.jpg", "/images/projects/ohtinskoe/photo-2.jpg", "/images/projects/ohtinskoe/photo-3.jpg", "/images/projects/ohtinskoe/photo-4.jpg"],
    plans: ["/images/projects/ohtinskoe/plan-1.jpg"],
    slug: "ohtinskoe",
    tags: ["gazobeton"],
    description: "2 ГАРДЕРОБНЫХ; ТЕРРАСА; КЛАДОВАЯ; СПОРТ. ЗАЛ; САУНА; КЛАДОВАЯ; КАБИНЕТ; ГАРАЖ; КОТЕЛЬНАЯ; ПОСТИРОЧНАЯ; КАБИНЕТ; КРЫЛЬЦО",
  },
  {
    id: 57,
    title: "Дом из газобетона (Ольгино)",
    nameOrig: "Ольгино",
    material: "Газобетон",
    area: 400,
    floors: 3,
    region: "СПб",
    year: 2023,
    price: "11 млн ₽",
    image: "/images/projects/olgino/photo-1.jpg",
    images: ["/images/projects/olgino/photo-1.jpg", "/images/projects/olgino/photo-2.jpg", "/images/projects/olgino/photo-3.webp", "/images/projects/olgino/photo-4.webp", "/images/projects/olgino/photo-5.webp", "/images/projects/olgino/photo-6.webp"],
    plans: ["/images/projects/olgino/plan-1.jpg", "/images/projects/olgino/plan-2.jpg", "/images/projects/olgino/plan-3.jpg"],
    slug: "olgino",
    tags: ["gazobeton"],
    description: "Терраса; Гардеробная; Кладовая; Мансарда",
  },
  {
    id: 58,
    title: "Дом из керамоблоков (Онегино)",
    nameOrig: "Онегино",
    material: "Керамоблок",
    area: 180,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "8,6 млн ₽",
    image: "/images/projects/onegino/photo-1.jpg",
    images: ["/images/projects/onegino/photo-1.jpg", "/images/projects/onegino/photo-2.jpg", "/images/projects/onegino/photo-3.jpg", "/images/projects/onegino/photo-4.jpg", "/images/projects/onegino/photo-5.jpg", "/images/projects/onegino/photo-6.jpg"],
    plans: ["/images/projects/onegino/plan-1.jpg"],
    slug: "onegino",
    tags: ["keramoblok"],
    description: "Котельная; Гардеробная; Терраса; Кабинет",
  },
  {
    id: 59,
    title: "Дом из газобетона (Пикколово)",
    nameOrig: "Пикколово",
    material: "Газобетон",
    area: 132,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7,7 млн ₽",
    image: "/images/projects/pikkolovo/photo-1.jpg",
    images: ["/images/projects/pikkolovo/photo-1.jpg", "/images/projects/pikkolovo/photo-2.jpg", "/images/projects/pikkolovo/photo-3.jpg", "/images/projects/pikkolovo/photo-4.jpg", "/images/projects/pikkolovo/photo-5.jpg"],
    plans: ["/images/projects/pikkolovo/plan-1.jpg"],
    slug: "pikkolovo",
    tags: ["gazobeton"],
    description: "ГАРДЕРОБНАЯ; КЛАДОВАЯ; КОТЕЛЬНАЯ; КРЫЛЬЦО; ТЕРРАСА",
  },
  {
    id: 60,
    title: "Дом из газобетона (Пушкин 2)",
    nameOrig: "Пушкин 2",
    material: "Газобетон",
    area: 322,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "11,2 млн ₽",
    image: "/images/projects/pushkin-2/photo-1.jpg",
    images: ["/images/projects/pushkin-2/photo-1.jpg", "/images/projects/pushkin-2/photo-2.jpg", "/images/projects/pushkin-2/photo-3.jpg", "/images/projects/pushkin-2/photo-4.jpg"],
    plans: ["/images/projects/pushkin-2/plan-1.jpg", "/images/projects/pushkin-2/plan-2.jpg"],
    slug: "pushkin-2",
    tags: ["gazobeton"],
    description: "4 ГАРДЕРОБНЫХ; САУНА; ХОЗ.ПОМЕЩЕНИЕ; НАВЕС; ТЕХ.ПОМЕЩЕНИЕ; КЛАДОВАЯ; ХОЛОДНАЯ КЛАДОВАЯ; ТЕРРАСА",
  },
  {
    id: 61,
    title: "Дом из газобетона (Парголово-Спасская)",
    nameOrig: "Парголово-Спасская",
    material: "Газобетон",
    area: 450,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "17,4 млн ₽",
    image: "/images/projects/pargolovo-spasskaya/photo-1.jpg",
    images: ["/images/projects/pargolovo-spasskaya/photo-1.jpg", "/images/projects/pargolovo-spasskaya/photo-10.jpg", "/images/projects/pargolovo-spasskaya/photo-2.jpg", "/images/projects/pargolovo-spasskaya/photo-3.jpg", "/images/projects/pargolovo-spasskaya/photo-4.jpg", "/images/projects/pargolovo-spasskaya/photo-5.jpg", "/images/projects/pargolovo-spasskaya/photo-6.jpg", "/images/projects/pargolovo-spasskaya/photo-7.jpg", "/images/projects/pargolovo-spasskaya/photo-8.jpg", "/images/projects/pargolovo-spasskaya/photo-9.jpg"],
    plans: ["/images/projects/pargolovo-spasskaya/plan-1.jpg", "/images/projects/pargolovo-spasskaya/plan-2.jpg"],
    slug: "pargolovo-spasskaya",
    tags: ["gazobeton"],
    description: "Котельная; 2 Гардеробных; Бильярдная; Постирочная; Терраса; Гараж; Кабинет",
  },
  {
    id: 62,
    title: "Дом из газобетона (Пестово Лайф)",
    nameOrig: "Пестово Лайф",
    material: "Газобетон",
    area: 248,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,3 млн ₽",
    image: "/images/projects/drachevo/photo-1.jpeg",
    images: ["/images/projects/drachevo/photo-1.jpeg", "/images/projects/drachevo/photo-2.jpeg", "/images/projects/drachevo/photo-3.jpeg", "/images/projects/drachevo/photo-4.jpeg", "/images/projects/drachevo/photo-5.png", "/images/projects/drachevo/photo-6.png", "/images/projects/drachevo/photo-7.jpg", "/images/projects/drachevo/photo-8.jpg", "/images/projects/drachevo/photo-9.jpg"],
    plans: ["/images/projects/drachevo/plan-1.jpg", "/images/projects/drachevo/plan-2.jpg"],
    slug: "drachevo",
    tags: ["gazobeton"],
    description: "Терраса; Гараж; Камин; Котельная; Балкон",
  },
  {
    id: 63,
    title: "Дом из газобетона (Плоское)",
    nameOrig: "Плоское",
    material: "Газобетон",
    area: 178,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,3 млн ₽",
    image: "/images/projects/ploskoe/photo-1.jpg",
    images: ["/images/projects/ploskoe/photo-1.jpg", "/images/projects/ploskoe/photo-10.jpg", "/images/projects/ploskoe/photo-11.jpg", "/images/projects/ploskoe/photo-2.jpg", "/images/projects/ploskoe/photo-3.jpg", "/images/projects/ploskoe/photo-4.jpg", "/images/projects/ploskoe/photo-5.jpg", "/images/projects/ploskoe/photo-6.jpg", "/images/projects/ploskoe/photo-7.jpg", "/images/projects/ploskoe/photo-8.jpg", "/images/projects/ploskoe/photo-9.jpg"],
    plans: ["/images/projects/ploskoe/plan-1.jpg", "/images/projects/ploskoe/plan-2.jpg"],
    slug: "ploskoe",
    tags: ["gazobeton"],
    description: "Терраса; Кладовая; Гардеробная; Лофт-зона; Второй свет",
  },
  {
    id: 64,
    title: "Дом из клееного бруса (Полесье)",
    nameOrig: "Полесье",
    material: "Клееный брус",
    area: 262,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "9,9 млн ₽",
    image: "/images/projects/polese/photo-1.jpg",
    images: ["/images/projects/polese/photo-1.jpg", "/images/projects/polese/photo-2.jpg", "/images/projects/polese/photo-3.jpg", "/images/projects/polese/photo-4.jpg"],
    plans: ["/images/projects/polese/plan-1.jpg", "/images/projects/polese/plan-2.jpg"],
    slug: "polese",
    tags: ["brus"],
    description: "Терраса; 3 балкона; Гардеробная; Сауна; Котельная",
  },
  {
    id: 65,
    title: "Дом из газобетона (Пушкин)",
    nameOrig: "Пушкин",
    material: "Газобетон",
    area: 148,
    floors: 3,
    region: "СПб",
    year: 2023,
    price: "6 млн ₽",
    image: "/images/projects/pushkin/photo-1.jpg",
    images: ["/images/projects/pushkin/photo-1.jpg", "/images/projects/pushkin/photo-2.jpg", "/images/projects/pushkin/photo-3.jpg", "/images/projects/pushkin/photo-4.jpg", "/images/projects/pushkin/photo-5.jpg"],
    plans: ["/images/projects/pushkin/plan-1.jpg", "/images/projects/pushkin/plan-2.jpg", "/images/projects/pushkin/plan-3.jpg"],
    slug: "pushkin",
    tags: ["gazobeton"],
    description: "Котельная; Терраса; Гардеробная; Сауна; Чердак",
  },
  {
    id: 66,
    title: "Дом из газобетона (Раздолье)",
    nameOrig: "Раздолье",
    material: "Газобетон",
    area: 126,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5,7 млн ₽",
    image: "/images/projects/razdole/photo-1.jpg",
    images: ["/images/projects/razdole/photo-1.jpg", "/images/projects/razdole/photo-2.jpg", "/images/projects/razdole/photo-3.jpg", "/images/projects/razdole/photo-4.jpg", "/images/projects/razdole/photo-5.jpg", "/images/projects/razdole/photo-6.jpg", "/images/projects/razdole/photo-7.jpg", "/images/projects/razdole/photo-8.jpg"],
    plans: ["/images/projects/razdole/plan-1.jpg", "/images/projects/razdole/plan-2.jpg"],
    slug: "razdole",
    tags: ["gazobeton"],
    description: "САУНА; ТЕРРАСА",
  },
  {
    id: 67,
    title: "Дом из газобетона (Рассколово)",
    nameOrig: "Рассколово",
    material: "Газобетон",
    area: 170,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5,2 млн ₽",
    image: "/images/projects/rasskolovo/photo-1.jpg",
    images: ["/images/projects/rasskolovo/photo-1.jpg", "/images/projects/rasskolovo/photo-2.jpg", "/images/projects/rasskolovo/photo-3.jpg", "/images/projects/rasskolovo/photo-4.jpg", "/images/projects/rasskolovo/photo-5.jpg"],
    plans: ["/images/projects/rasskolovo/plan-1.jpg", "/images/projects/rasskolovo/plan-2.jpg"],
    slug: "rasskolovo",
    tags: ["gazobeton"],
    description: "2 КРЫЛЬЦА; КОТЕЛЬНАЯ; ТЕРРАСА",
  },
  {
    id: 68,
    title: "Дом из газобетона (Репино 399)",
    nameOrig: "Репино 399",
    material: "Газобетон",
    area: 153,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7,1 млн ₽",
    image: "/images/projects/repino-399/photo-1.jpg",
    images: ["/images/projects/repino-399/photo-1.jpg", "/images/projects/repino-399/photo-2.jpg", "/images/projects/repino-399/photo-3.jpg", "/images/projects/repino-399/photo-4.jpg"],
    plans: ["/images/projects/repino-399/plan-1.jpg"],
    slug: "repino-399",
    tags: ["gazobeton"],
    description: "САУНА; КОТЕЛЬНАЯ; ТЕРРАСА; ГАРДЕРОБНАЯ",
  },
  {
    id: 69,
    title: "Дом из газобетона (Романово)",
    nameOrig: "Романово",
    material: "Газобетон",
    area: 252,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "12,1 млн ₽",
    image: "/images/projects/romanovo/photo-1.jpeg",
    images: ["/images/projects/romanovo/photo-1.jpeg", "/images/projects/romanovo/photo-2.jpeg", "/images/projects/romanovo/photo-3.jpeg", "/images/projects/romanovo/photo-4.jpeg", "/images/projects/romanovo/photo-5.jpeg", "/images/projects/romanovo/photo-6.jpeg"],
    plans: [],
    slug: "romanovo",
    tags: ["gazobeton"],
    description: "КОТЕЛЬНАЯ; МАСТЕРСКАЯ; КЛАДОВАЯ; ГАРДЕРОБНАЯ; ТЕРРАСА",
  },
  {
    id: 70,
    title: "Дом из газобетона (Репино 289)",
    nameOrig: "Репино 289",
    material: "Газобетон",
    area: 334,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "12,9 млн ₽",
    image: "/images/projects/repino-park-1/photo-1.jpg",
    images: ["/images/projects/repino-park-1/photo-1.jpg", "/images/projects/repino-park-1/photo-10.jpg", "/images/projects/repino-park-1/photo-2.jpg", "/images/projects/repino-park-1/photo-3.jpg", "/images/projects/repino-park-1/photo-4.jpg", "/images/projects/repino-park-1/photo-5.jpg", "/images/projects/repino-park-1/photo-6.jpg", "/images/projects/repino-park-1/photo-7.jpg", "/images/projects/repino-park-1/photo-8.jpg", "/images/projects/repino-park-1/photo-9.jpg"],
    plans: ["/images/projects/repino-park-1/plan-1.jpg", "/images/projects/repino-park-1/plan-2.jpg"],
    slug: "repino-park-1",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Балкон; Гараж; Терраса; Кабинет",
  },
  {
    id: 71,
    title: "Дом из керамоблоков (Репино 292)",
    nameOrig: "Репино 292",
    material: "Керамоблок",
    area: 401,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "11,9 млн ₽",
    image: "/images/projects/repino-2/photo-1.jpg",
    images: ["/images/projects/repino-2/photo-1.jpg", "/images/projects/repino-2/photo-10.jpg", "/images/projects/repino-2/photo-2.jpg", "/images/projects/repino-2/photo-3.jpg", "/images/projects/repino-2/photo-4.jpg", "/images/projects/repino-2/photo-5.jpg", "/images/projects/repino-2/photo-6.jpg", "/images/projects/repino-2/photo-7.jpg", "/images/projects/repino-2/photo-8.jpg", "/images/projects/repino-2/photo-9.jpg"],
    plans: [],
    slug: "repino-2",
    tags: ["keramoblok"],
    description: "Котельная; 2 Гардеробных; Бильярдная; Постирочная; Терраса; Библиотека",
  },
  {
    id: 72,
    title: "Дом из газобетона (Репино 398)",
    nameOrig: "Репино 398",
    material: "Газобетон",
    area: 249,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "9,7 млн ₽",
    image: "/images/projects/repino/photo-1.jpg",
    images: ["/images/projects/repino/photo-1.jpg", "/images/projects/repino/photo-10.jpg", "/images/projects/repino/photo-2.jpg", "/images/projects/repino/photo-3.jpg", "/images/projects/repino/photo-4.jpg", "/images/projects/repino/photo-5.jpg", "/images/projects/repino/photo-6.jpg", "/images/projects/repino/photo-7.jpg", "/images/projects/repino/photo-8.jpg", "/images/projects/repino/photo-9.jpg"],
    plans: ["/images/projects/repino/plan-1.jpg"],
    slug: "repino",
    tags: ["gazobeton"],
    description: "Котельная; 3 Террасы; Гардеробная; Сауна; Техкомната; Холодильная камера",
  },
  {
    id: 73,
    title: "Дом из клееного бруса (Репино Парк 191)",
    nameOrig: "Репино Парк 191",
    material: "Клееный брус",
    area: 243,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "12,7 млн ₽",
    image: "/images/projects/repino-park-191/photo-1.jpeg",
    images: ["/images/projects/repino-park-191/photo-1.jpeg", "/images/projects/repino-park-191/photo-2.jpeg", "/images/projects/repino-park-191/photo-3.jpeg", "/images/projects/repino-park-191/photo-4.jpeg", "/images/projects/repino-park-191/photo-5.jpg", "/images/projects/repino-park-191/photo-6.jpg", "/images/projects/repino-park-191/photo-7.jpg", "/images/projects/repino-park-191/photo-8.jpg"],
    plans: ["/images/projects/repino-park-191/plan-1.jpg", "/images/projects/repino-park-191/plan-2.jpg"],
    slug: "repino-park-191",
    tags: ["brus"],
    description: "Терраса; Крыльцо; Котельная; Гардеробная",
  },
  {
    id: 74,
    title: "Дом из газобетона (Рехколово)",
    nameOrig: "Рехколово",
    material: "Газобетон",
    area: 294,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "9,8 млн ₽",
    image: "/images/projects/rehkolovo/photo-1.jpg",
    images: ["/images/projects/rehkolovo/photo-1.jpg", "/images/projects/rehkolovo/photo-2.jpg", "/images/projects/rehkolovo/photo-3.jpg", "/images/projects/rehkolovo/photo-4.jpg"],
    plans: ["/images/projects/rehkolovo/plan-1.jpg", "/images/projects/rehkolovo/plan-2.jpg"],
    slug: "rehkolovo",
    tags: ["gazobeton"],
    description: "Терраса; Гардеробная; Балкон; Постирочная; Кладовая; Крыльцо",
  },
  {
    id: 75,
    title: "Дом из клееного бруса (Рощино)",
    nameOrig: "Рощино",
    material: "Клееный брус",
    area: 128,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7 млн ₽",
    image: "/images/projects/roshhino/photo-1.jpeg",
    images: ["/images/projects/roshhino/photo-1.jpeg", "/images/projects/roshhino/photo-2.jpeg", "/images/projects/roshhino/photo-3.jpeg", "/images/projects/roshhino/photo-4.jpeg", "/images/projects/roshhino/photo-5.jpg", "/images/projects/roshhino/photo-6.jpg", "/images/projects/roshhino/photo-7.jpg", "/images/projects/roshhino/photo-8.jpg"],
    plans: ["/images/projects/roshhino/plan-1.jpg"],
    slug: "roshhino",
    tags: ["brus"],
    description: "Терраса; Крыльцо; Кладовая",
  },
  {
    id: 76,
    title: "Дом из газобетона (Салтыковка)",
    nameOrig: "Салтыковка",
    material: "Газобетон",
    area: 216,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "8,6 млн ₽",
    image: "/images/projects/saltykovka/photo-1.jpg",
    images: ["/images/projects/saltykovka/photo-1.jpg", "/images/projects/saltykovka/photo-2.jpg", "/images/projects/saltykovka/photo-3.jpg", "/images/projects/saltykovka/photo-4.jpg"],
    plans: ["/images/projects/saltykovka/plan-1.jpg", "/images/projects/saltykovka/plan-2.jpg"],
    slug: "saltykovka",
    tags: ["gazobeton"],
    description: "КОТЕЛЬНАЯ; КЛАДОВАЯ; КРЫЛЬЦО; ТЕРРАСА; ГАРДЕРОБНАЯ",
  },
  {
    id: 77,
    title: "Дом из газобетона (Самара)",
    nameOrig: "Самара",
    material: "Газобетон",
    area: 240,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "8,7 млн ₽",
    image: "/images/projects/samara/photo-1.jpg",
    images: ["/images/projects/samara/photo-1.jpg", "/images/projects/samara/photo-2.jpg", "/images/projects/samara/photo-3.jpg", "/images/projects/samara/photo-4.jpg", "/images/projects/samara/photo-5.jpg"],
    plans: ["/images/projects/samara/plan-1.jpg", "/images/projects/samara/plan-2.jpg"],
    slug: "samara",
    tags: ["gazobeton"],
    description: "Терраса; Котельная; Кладовая; Парная; Гардеробная; Балкон",
  },
  {
    id: 78,
    title: "Дом из газобетона (Скотное 522)",
    nameOrig: "Скотное 522",
    material: "Газобетон",
    area: 122,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5 млн ₽",
    image: "/images/projects/skotnoe-522/photo-1.jpg",
    images: ["/images/projects/skotnoe-522/photo-1.jpg", "/images/projects/skotnoe-522/photo-2.jpg", "/images/projects/skotnoe-522/photo-3.jpg", "/images/projects/skotnoe-522/photo-4.jpg"],
    plans: ["/images/projects/skotnoe-522/plan-1.jpg"],
    slug: "skotnoe-522",
    tags: ["gazobeton"],
    description: "ТЕРРАСА; КЛАДОВАЯ",
  },
  {
    id: 79,
    title: "Дом из газобетона (Скотное 523)",
    nameOrig: "Скотное 523",
    material: "Газобетон",
    area: 117,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "4,9 млн ₽",
    image: "/images/projects/skotnoe-523/photo-1.jpg",
    images: ["/images/projects/skotnoe-523/photo-1.jpg", "/images/projects/skotnoe-523/photo-2.jpg", "/images/projects/skotnoe-523/photo-3.jpg", "/images/projects/skotnoe-523/photo-4.jpg"],
    plans: ["/images/projects/skotnoe-523/plan-1.jpg"],
    slug: "skotnoe-523",
    tags: ["gazobeton"],
    description: "ТЕРРАСА; КОТЕЛЬНАЯ",
  },
  {
    id: 80,
    title: "Дом из газобетона (Саввино)",
    nameOrig: "Саввино",
    material: "Газобетон",
    area: 188,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,7 млн ₽",
    image: "/images/projects/savvino/photo-1.jpeg",
    images: ["/images/projects/savvino/photo-1.jpeg", "/images/projects/savvino/photo-2.jpeg", "/images/projects/savvino/photo-3.jpeg", "/images/projects/savvino/photo-4.jpeg", "/images/projects/savvino/photo-5.webp", "/images/projects/savvino/photo-6.webp"],
    plans: ["/images/projects/savvino/plan-1.jpg", "/images/projects/savvino/plan-2.jpg"],
    slug: "savvino",
    tags: ["gazobeton"],
    description: "Терраса; Гардеробная; Эркер; Кладовая",
  },
  {
    id: 81,
    title: "Дом из клееного бруса (Садко)",
    nameOrig: "Садко",
    material: "Клееный брус",
    area: 175,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,1 млн ₽",
    image: "/images/projects/sadko/photo-1.jpg",
    images: ["/images/projects/sadko/photo-1.jpg", "/images/projects/sadko/photo-2.jpg", "/images/projects/sadko/photo-3.jpg", "/images/projects/sadko/photo-4.jpg"],
    plans: ["/images/projects/sadko/plan-1.jpg", "/images/projects/sadko/plan-2.jpg"],
    slug: "sadko",
    tags: ["brus"],
    description: "Терраса; Котельная; Постирочная; Сауна; Кладовая",
  },
  {
    id: 82,
    title: "Дом из газобетона (Северное Сияние)",
    nameOrig: "Северное Сияние",
    material: "Газобетон",
    area: 241,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "12 млн ₽",
    image: "/images/projects/severnoe-siyanie/photo-1.jpg",
    images: ["/images/projects/severnoe-siyanie/photo-1.jpg", "/images/projects/severnoe-siyanie/photo-2.jpg", "/images/projects/severnoe-siyanie/photo-3.jpg", "/images/projects/severnoe-siyanie/photo-4.jpg", "/images/projects/severnoe-siyanie/photo-5.jpg", "/images/projects/severnoe-siyanie/photo-6.jpg", "/images/projects/severnoe-siyanie/photo-7.jpg"],
    plans: ["/images/projects/severnoe-siyanie/plan-1.jpg", "/images/projects/severnoe-siyanie/plan-2.jpg"],
    slug: "severnoe-siyanie",
    tags: ["gazobeton"],
    description: "Бойлерная; Гардеробная; Сауна; Кабинет; 2 Крыльца",
  },
  {
    id: 83,
    title: "Дом из газобетона (Скворицы)",
    nameOrig: "Скворицы",
    material: "Газобетон",
    area: 232,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "10,5 млн ₽",
    image: "/images/projects/skvoriczy/photo-1.jpg",
    images: ["/images/projects/skvoriczy/photo-1.jpg", "/images/projects/skvoriczy/photo-2.jpg", "/images/projects/skvoriczy/photo-3.jpg", "/images/projects/skvoriczy/photo-4.jpg", "/images/projects/skvoriczy/photo-5.jpg", "/images/projects/skvoriczy/photo-6.jpg"],
    plans: ["/images/projects/skvoriczy/plan-1.jpg"],
    slug: "skvoriczy",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Парная; Терраса; Комната отдыха",
  },
  {
    id: 84,
    title: "Дом из газобетона (Софийские Сады)",
    nameOrig: "Софийские Сады",
    material: "Газобетон",
    area: 136,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5,3 млн ₽",
    image: "/images/projects/sofijskie-sady/photo-1.jpg",
    images: ["/images/projects/sofijskie-sady/photo-1.jpg", "/images/projects/sofijskie-sady/photo-2.jpg", "/images/projects/sofijskie-sady/photo-3.jpg", "/images/projects/sofijskie-sady/photo-4.jpg", "/images/projects/sofijskie-sady/photo-5.jpg", "/images/projects/sofijskie-sady/photo-6.jpg", "/images/projects/sofijskie-sady/photo-7.jpg", "/images/projects/sofijskie-sady/photo-8.jpg"],
    plans: ["/images/projects/sofijskie-sady/plan-1.jpg"],
    slug: "sofijskie-sady",
    tags: ["gazobeton"],
    description: "Котельная; Терраса; Мастерская; Крыльцо",
  },
  {
    id: 85,
    title: "Дом из газобетона (Степаньково)",
    nameOrig: "Степаньково",
    material: "Газобетон",
    area: 261,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "8,7 млн ₽",
    image: "/images/projects/stepankovo/photo-1.jpeg",
    images: ["/images/projects/stepankovo/photo-1.jpeg", "/images/projects/stepankovo/photo-2.jpeg", "/images/projects/stepankovo/photo-3.jpeg", "/images/projects/stepankovo/photo-4.jpeg", "/images/projects/stepankovo/photo-5.jpg", "/images/projects/stepankovo/photo-6.jpg", "/images/projects/stepankovo/photo-7.jpg"],
    plans: ["/images/projects/stepankovo/plan-1.jpg", "/images/projects/stepankovo/plan-2.jpg"],
    slug: "stepankovo",
    tags: ["gazobeton"],
    description: "Котельная; Гардеробная; Гараж; Балкон; Сауна/Хамам; Эркер",
  },
  {
    id: 86,
    title: "Дом из газобетона (Узигонты)",
    nameOrig: "Узигонты",
    material: "Газобетон",
    area: 451,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "23,2 млн ₽",
    image: "/images/projects/uzigontu/photo-1.jpg",
    images: ["/images/projects/uzigontu/photo-1.jpg", "/images/projects/uzigontu/photo-10.jpg", "/images/projects/uzigontu/photo-11.jpg", "/images/projects/uzigontu/photo-12.jpg", "/images/projects/uzigontu/photo-2.jpg", "/images/projects/uzigontu/photo-3.jpg", "/images/projects/uzigontu/photo-4.jpg", "/images/projects/uzigontu/photo-5.jpg", "/images/projects/uzigontu/photo-6.jpg", "/images/projects/uzigontu/photo-7.jpg", "/images/projects/uzigontu/photo-8.jpg", "/images/projects/uzigontu/photo-9.jpg"],
    plans: ["/images/projects/uzigontu/plan-1.jpg", "/images/projects/uzigontu/plan-2.jpg"],
    slug: "uzigontu",
    tags: ["gazobeton"],
    description: "Котельная; 5 Гардеробных; Сауна; Бассейн; Балкон; Терраса; Тренажерный зал; Гараж",
  },
  {
    id: 87,
    title: "Дом из газобетона (Федоскино)",
    nameOrig: "Федоскино",
    material: "Газобетон",
    area: 220,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "7,7 млн ₽",
    image: "/images/projects/fedoskino/photo-1.jpeg",
    images: ["/images/projects/fedoskino/photo-1.jpeg", "/images/projects/fedoskino/photo-2.jpeg", "/images/projects/fedoskino/photo-3.jpeg", "/images/projects/fedoskino/photo-4.jpeg", "/images/projects/fedoskino/photo-5.jpg", "/images/projects/fedoskino/photo-6.jpg", "/images/projects/fedoskino/photo-7.jpg", "/images/projects/fedoskino/photo-8.jpg"],
    plans: ["/images/projects/fedoskino/plan-1.jpg", "/images/projects/fedoskino/plan-2.jpg"],
    slug: "fedoskino",
    tags: ["gazobeton"],
    description: "Терраса; Эркер; Гардеробная; Котельная",
  },
  {
    id: 88,
    title: "Дом из газобетона (Четверяково)",
    nameOrig: "Четверяково",
    material: "Газобетон",
    area: 210,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "5,9 млн ₽",
    image: "/images/projects/chetveryakovo/photo-1.jpg",
    images: ["/images/projects/chetveryakovo/photo-1.jpg", "/images/projects/chetveryakovo/photo-2.jpg", "/images/projects/chetveryakovo/photo-3.jpg", "/images/projects/chetveryakovo/photo-4.jpg", "/images/projects/chetveryakovo/photo-5.jpg"],
    plans: ["/images/projects/chetveryakovo/plan-1.jpg", "/images/projects/chetveryakovo/plan-2.jpg"],
    slug: "chetveryakovo",
    tags: ["gazobeton"],
    description: "КЛАДОВАЯ; ГАРДЕРОБНАЯ; ТЕРРАСА; КРЫЛЬЦО",
  },
  {
    id: 89,
    title: "Дом из клееного бруса (Чайка)",
    nameOrig: "Чайка",
    material: "Клееный брус",
    area: 215,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "9 млн ₽",
    image: "/images/projects/chajka/photo-1.jpg",
    images: ["/images/projects/chajka/photo-1.jpg", "/images/projects/chajka/photo-2.jpg", "/images/projects/chajka/photo-3.jpg", "/images/projects/chajka/photo-4.jpg"],
    plans: ["/images/projects/chajka/plan-1.jpg", "/images/projects/chajka/plan-2.jpg"],
    slug: "chajka",
    tags: ["brus"],
    description: "Терраса; Котельная; Эркер; Второй Свет",
  },
  {
    id: 90,
    title: "Дом из газобетона (Шале)",
    nameOrig: "Шале",
    material: "Газобетон",
    area: 156,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6,8 млн ₽",
    image: "/images/projects/shale/photo-1.jpg",
    images: ["/images/projects/shale/photo-1.jpg", "/images/projects/shale/photo-2.jpg", "/images/projects/shale/photo-3.jpg", "/images/projects/shale/photo-4.jpg"],
    plans: ["/images/projects/shale/plan-1.jpg", "/images/projects/shale/plan-2.jpg"],
    slug: "shale",
    tags: ["gazobeton"],
    description: "2 ГАРДЕРОБА; 2 КРЫЛЬЦО; ТЕРРАСА; БАЛКОН; КОТЕЛЬНАЯ",
  },
  {
    id: 91,
    title: "Дом из газобетона (Шапки)",
    nameOrig: "Шапки",
    material: "Газобетон",
    area: 166,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7,1 млн ₽",
    image: "/images/projects/shapki/photo-1.jpg",
    images: ["/images/projects/shapki/photo-1.jpg", "/images/projects/shapki/photo-2.jpg", "/images/projects/shapki/photo-3.jpg", "/images/projects/shapki/photo-4.jpg", "/images/projects/shapki/photo-5.jpg"],
    plans: ["/images/projects/shapki/plan-1.jpg"],
    slug: "shapki",
    tags: ["gazobeton"],
    description: "САУНА; ГАРДЕРОБНАЯ; КОТЕЛЬНАЯ; ГАРАЖ; ТЕРРАСА; КРЫЛЬЦО",
  },
  {
    id: 92,
    title: "Дом из газобетона (Электроугли)",
    nameOrig: "Электроугли",
    material: "Газобетон",
    area: 173,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "7 млн ₽",
    image: "/images/projects/elektrougli/photo-1.jpg",
    images: ["/images/projects/elektrougli/photo-1.jpg", "/images/projects/elektrougli/photo-2.jpg", "/images/projects/elektrougli/photo-3.jpg", "/images/projects/elektrougli/photo-4.jpg"],
    plans: ["/images/projects/elektrougli/plan-1.jpg"],
    slug: "elektrougli",
    tags: ["gazobeton"],
    description: "ГАРДЕРОБНАЯ; КЛАДОВАЯ",
  },
  {
    id: 93,
    title: "Дом из газобетона (Юкки-Сити)",
    nameOrig: "Юкки-Сити",
    material: "Газобетон",
    area: 261,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "11,5 млн ₽",
    image: "/images/projects/yukki-siti/photo-1.jpg",
    images: ["/images/projects/yukki-siti/photo-1.jpg", "/images/projects/yukki-siti/photo-2.jpg", "/images/projects/yukki-siti/photo-3.jpg", "/images/projects/yukki-siti/photo-4.jpg", "/images/projects/yukki-siti/photo-5.jpg", "/images/projects/yukki-siti/photo-6.jpg", "/images/projects/yukki-siti/photo-7.jpg", "/images/projects/yukki-siti/photo-8.jpg"],
    plans: ["/images/projects/yukki-siti/plan-1.jpg", "/images/projects/yukki-siti/plan-2.jpg"],
    slug: "yukki-siti",
    tags: ["gazobeton"],
    description: "Котельная; Терраса; Гардеробная; Мастер-спальня; Кладовая",
  },
  {
    id: 94,
    title: "Дом из газобетона (Юкковское)",
    nameOrig: "Юкковское",
    material: "Газобетон",
    area: 344,
    floors: 2,
    region: "СПб",
    year: 2023,
    price: "13,4 млн ₽",
    image: "/images/projects/yukkovskoe/photo-1.jpg",
    images: ["/images/projects/yukkovskoe/photo-1.jpg", "/images/projects/yukkovskoe/photo-2.jpg", "/images/projects/yukkovskoe/photo-3.jpg", "/images/projects/yukkovskoe/photo-4.jpg", "/images/projects/yukkovskoe/photo-5.jpg", "/images/projects/yukkovskoe/photo-6.jpg", "/images/projects/yukkovskoe/photo-7.jpg", "/images/projects/yukkovskoe/photo-8.jpg", "/images/projects/yukkovskoe/photo-9.jpg"],
    plans: ["/images/projects/yukkovskoe/plan-1.jpg", "/images/projects/yukkovskoe/plan-2.jpg"],
    slug: "yukkovskoe",
    tags: ["gazobeton"],
    description: "Винокурня; 3 Террасы; 3 Гардеробных; Постирочная; Детская",
  },
  {
    id: 95,
    title: "Дом из газобетона (Ям Ижора)",
    nameOrig: "Ям Ижора",
    material: "Газобетон",
    area: 201,
    floors: 1,
    region: "СПб",
    year: 2023,
    price: "6,8 млн ₽",
    image: "/images/projects/yam-izhora/photo-1.jpg",
    images: ["/images/projects/yam-izhora/photo-1.jpg", "/images/projects/yam-izhora/photo-2.jpg", "/images/projects/yam-izhora/photo-3.jpg", "/images/projects/yam-izhora/photo-4.jpg", "/images/projects/yam-izhora/photo-5.jpg", "/images/projects/yam-izhora/photo-6.jpg"],
    plans: ["/images/projects/yam-izhora/plan-1.jpg", "/images/projects/yam-izhora/plan-2.jpg"],
    slug: "yam-izhora",
    tags: ["gazobeton"],
    description: "2 ТЕРРАСЫ; КОТЕЛЬНАЯ; ГАРДЕРОБНАЯ",
  }
];

// ─── ОТЗЫВЫ ─────────────────────────────────────────────────────────────────
export const reviews = [
  {
    id: 1,
    name: "Александр Петров",
    city: "Пушкин, СПб",
    area: 180,
    material: "Газобетон",
    year: 2024,
    rating: 5,
    text: "Строили дом почти год. На протяжении всего процесса получал еженедельные фотоотчёты — это очень успокаивало. Смета не изменилась ни на рубль. Именно так и должно работать строительство.",
    image: "/images/projects/p01.jpg",
  },
  {
    id: 2,
    name: "Елена Соколова",
    city: "Всеволожск, ЛО",
    area: 140,
    material: "Газобетон",
    year: 2024,
    rating: 5,
    text: "Изначально боялась подрядчиков — слышала много историй про допсметы. В Петрострое всё оказалось иначе: приехал специалист, посмотрел участок, дал реальную цену. Итог — в рамках бюджета.",
    image: "/images/projects/p02.jpg",
  },
  {
    id: 3,
    name: "Михаил Громов",
    city: "Красногорск, МО",
    area: 300,
    material: "Кирпич",
    year: 2023,
    rating: 5,
    text: "Выбирал между тремя компаниями. Петрострой единственные, кто предложил показать живой объект до подписания договора. Поехали, посмотрели — решение приняли сразу. Уже два года в доме, никаких нареканий.",
    image: "/images/projects/p44.jpg",
  },
];

// ─── FAQ ─────────────────────────────────────────────────────────────────────
export const faqItems = [
  {
    category: "Цена и смета",
    questions: [
      {
        q: "Почему ваша цена может отличаться от цен конкурентов?",
        a: "Мы называем реальную цену сразу, без занижения ради привлечения клиента. Многие компании дают низкую стартовую смету, а потом добирают на дополнениях. У нас смета в договоре = смета на финише.",
      },
      {
        q: "Что входит в стоимость «под ключ»?",
        a: "Фундамент, стены, перекрытия, кровля, окна, двери, инженерные системы (отопление, водоснабжение, электрика, канализация), черновая и чистовая отделка.",
      },
      {
        q: "Можно ли получить смету без выезда специалиста?",
        a: "Ориентировочный диапазон — рассчитайте в нашем квизе за 2 минуты. Точная смета составляется после бесплатного выезда на участок.",
      },
      {
        q: "Бывают ли скрытые платежи или допсметы?",
        a: "Нет. Дополнительные работы возникают только если вы сами захотите что-то изменить по ходу строительства.",
      },
    ],
  },
  {
    category: "Процесс работы",
    questions: [
      {
        q: "Сколько времени занимает строительство дома?",
        a: "Газобетонный дом 150 м² — 6–8 месяцев. Кирпичный 200 м² — 10–12 месяцев. Точные сроки фиксируются в договоре.",
      },
      {
        q: "Как я могу контролировать ход строительства?",
        a: "Каждую неделю вы получаете фотоотчёт с объекта. Также можно приехать на объект в любой рабочий день.",
      },
      {
        q: "Что происходит после подачи заявки?",
        a: "1. Перезваниваем за 30 минут. 2. Бесплатный выезд специалиста. 3. Смета за 3 рабочих дня. 4. Договор с фиксированной ценой.",
      },
    ],
  },
  {
    category: "Гарантии",
    questions: [
      {
        q: "Какая гарантия на дом?",
        a: "10 лет на несущие конструкции, 3 года на инженерные системы, 1 год на отделочные работы. Всё прописывается в гарантийном паспорте.",
      },
      {
        q: "Что делать, если возникнет гарантийный случай?",
        a: "Звоните или пишите — в течение 3 рабочих дней приезжает специалист, составляет акт и согласовывает сроки устранения.",
      },
    ],
  },
  {
    category: "Ипотека",
    questions: [
      {
        q: "Можно ли строить дом в ипотеку?",
        a: "Да. Работаем с семейной ипотекой (от 6%), льготной программой и рассрочкой от компании.",
      },
      {
        q: "Какие банки-партнёры у вас есть?",
        a: "Сбербанк, ВТБ, Альфа-Банк, ДОМ.РФ, Россельхозбанк.",
      },
    ],
  },
  {
    category: "Технологии",
    questions: [
      {
        q: "Чем газобетон лучше кирпича?",
        a: "Газобетон теплее, строится быстрее, дешевле. Кирпич долговечнее, статуснее. Выбор зависит от бюджета и приоритетов.",
      },
      {
        q: "Вы строите по проектам других компаний?",
        a: "Да, но рекомендуем проектирование у нас — делаем под свою технологию, нет расхождений.",
      },
    ],
  },
];

// ─── МАТРИЦА ЦЕН ─────────────────────────────────────────────────────────────
export const priceMatrix = [
  {
    material: "Газобетон",
    packages: [
      { name: "Холодный контур", price: "от 4 800 ₽/м²", includes: ["Фундамент", "Стены газобетон D500", "Кровля", "Окна ПВХ", "Входная дверь"] },
      { name: "Тёплый контур",   price: "от 7 200 ₽/м²", includes: ["Холодный контур", "Утепление", "Отопление", "Водоснабжение", "Электрика"] },
      { name: "White Box",       price: "от 10 500 ₽/м²", includes: ["Тёплый контур", "Стяжка", "Штукатурка", "Разводка под отделку"] },
      { name: "Под ключ",        price: "от 14 000 ₽/м²", includes: ["White Box", "Чистовая отделка", "Сантехника", "Двери"] },
    ],
  },
  {
    material: "Кирпич",
    packages: [
      { name: "Холодный контур", price: "от 7 500 ₽/м²", includes: ["Фундамент", "Кирпичные стены", "Кровля", "Окна ПВХ", "Входная дверь"] },
      { name: "Тёплый контур",   price: "от 10 500 ₽/м²", includes: ["Холодный контур", "Утепление", "Отопление", "Водоснабжение", "Электрика"] },
      { name: "White Box",       price: "от 14 000 ₽/м²", includes: ["Тёплый контур", "Стяжка", "Штукатурка", "Разводка"] },
      { name: "Под ключ",        price: "от 18 500 ₽/м²", includes: ["White Box", "Чистовая отделка", "Сантехника", "Двери"] },
    ],
  },
  {
    material: "Керамоблок",
    packages: [
      { name: "Холодный контур", price: "от 6 200 ₽/м²", includes: ["Фундамент", "Стены керамоблок", "Кровля", "Окна ПВХ", "Входная дверь"] },
      { name: "Тёплый контур",   price: "от 9 000 ₽/м²", includes: ["Холодный контур", "Утепление", "Отопление", "Водоснабжение", "Электрика"] },
      { name: "White Box",       price: "от 12 500 ₽/м²", includes: ["Тёплый контур", "Стяжка", "Штукатурка", "Разводка"] },
      { name: "Под ключ",        price: "от 16 000 ₽/м²", includes: ["White Box", "Чистовая отделка", "Сантехника", "Двери"] },
    ],
  },
  {
    material: "Клееный брус",
    packages: [
      { name: "Холодный контур", price: "от 5 500 ₽/м²", includes: ["Фундамент", "Стены клееный брус", "Кровля", "Окна ПВХ", "Входная дверь"] },
      { name: "Тёплый контур",   price: "от 8 200 ₽/м²", includes: ["Холодный контур", "Утепление", "Отопление", "Водоснабжение", "Электрика"] },
      { name: "White Box",       price: "от 11 500 ₽/м²", includes: ["Тёплый контур", "Стяжка", "Чистовые полы", "Разводка"] },
      { name: "Под ключ",        price: "от 15 000 ₽/м²", includes: ["White Box", "Чистовая отделка", "Сантехника", "Двери"] },
    ],
  },
];

// ─── СОТРУДНИКИ ───────────────────────────────────────────────────────────────
export const teamMembers = [
  {
    name: "Дмитрий",
    role: "Руководитель отдела продаж",
    photo: "/images/staff/dmitriy.jpg",
    city: "СПб",
  },
  {
    name: "Павел Ременников",
    role: "Директор по развитию (МСК)",
    photo: "/images/staff/pavel.jpg",
    city: "Москва",
  },
  {
    name: "Артём Белоусов",
    role: "Прораб (Москва)",
    photo: "/images/staff/artem.jpg",
    city: "Москва",
  },
  {
    name: "Илья Мартьянов",
    role: "Прораб",
    photo: "/images/staff/ilya.jpg",
    city: "СПб",
  },
  {
    name: "Эдуард Белоусов",
    role: "Прораб (МСК)",
    photo: "/images/staff/eduard.jpg",
    city: "Москва",
  },
  {
    name: "Виктория Бурмистрова",
    role: "Инженер ПТО",
    photo: "/images/staff/viktoriya.jpg",
    city: "СПб",
  },
  {
    name: "Александр Буркин",
    role: "Инженер ПТО",
    photo: "/images/staff/aleksandr.jpg",
    city: "СПб",
  },
  {
    name: "Максим",
    role: "Специалист по строительству",
    photo: "/images/staff/maksim.jpg",
    city: "СПб",
  },
];
